### ISSUE TITLE
关于雪地行走轨迹的问题

### ISSUE THREAD

**Issue by yangyongwff** [chenjd/Unity-Miscellaneous-Shaders#3]
你好，我最近看到雪地行走的Demo，想学习一下。项目在我的Unity5.5.3打开之后，ExplosionAnSandEffect场景的效果正常，但是雪地行走这个看不到移动轨迹不知道是怎么回事呀？这是打开后的效果。
![360 20171222101922488](https://user-images.githubusercontent.com/22364186/34282613-cafcd810-e701-11e7-8a77-bc5dad846ce7.jpg)

**Comment by chenjd** [comment]
最好和我的unity版本一致
